"""Pdf Plumber Parsing RFQ 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztcU_CCfaMTOKzVfr61w9XXtGorlJxns
"""

import pandas as pd


def extract_tables_from_pdf(path):
    import pandas as pd
    import pdfplumber

    dfs = []

    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            tables = page.extract_tables()

            for table in tables:
                df = pd.DataFrame(table)
                dfs.append(df)

    return dfs


def normalize_tables(dfs):
    all_rows = []

    for df in dfs:
        # skip header (row 0 dan 1)
        df_data = df.iloc[2:].copy()

        # ambil kolom penting
        df_data = df_data[[4, 5, 6]]

        df_data.columns = ["description", "uom", "qty"]

        all_rows.append(df_data)

    final_df = pd.concat(all_rows, ignore_index=True)

    return final_df


def clean_dataframe(df):
    import re

    # drop kosong
    df = df.dropna(subset=["description"])

    # clean description
    df["description"] = df["description"].apply(lambda x: str(x))

    df["description"] = df["description"].apply(
        lambda x: re.sub(r"Buyer Comments.*", "", x, flags=re.IGNORECASE)
    )

    df["description"] = df["description"].apply(
        lambda x: re.sub(r"-UOM:.*", "", x, flags=re.IGNORECASE)
    )

    df["description"] = df["description"].str.strip()

    # clean uom
    df["uom"] = df["uom"].str.strip()

    # clean qty
    df["qty"] = pd.to_numeric(df["qty"], errors="coerce")

    return df.reset_index(drop=True)


def parse_rfq_pdf_structured(path):
    dfs = extract_tables_from_pdf(path)

    df = normalize_tables(dfs)

    df = clean_dataframe(df)

    return df
