[program:rfq-parser]
command=/home/arifrahmanrhm/rfq-parser-matching-be-fastapi/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000
directory=/home/arifrahmanrhm/rfq-parser-matching-be-fastapi
user=arifrahmanrhm
autostart=true
autorestart=true
stderr_logfile=/var/log/rfq-parser.err.log
stdout_logfile=/var/log/rfq-parser.out.log
